name: My GitHub Actions Pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: roots/issue-closer-action@v1.1
    - name: Build code
      run: <BUILD>
